types:
  - build

Build_rpm:
  type: build
  image: gvangool/rpmbuilder:centos7
  only:
    - tags
  script:
    - yum install -y libevent-devel
    - rpmbuild -bb -D "git_tag $CI_BUILD_TAG" slarht.spec
    - pwd
    - ls
    - curl -T *.rpm amoshi.ru/api/repo
